target: "example.com"

threads: 50
timeout: 10

wordlists:
  subdomain: "/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt"
  api: "/usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt"

output:
  folder: "output"
